sudo: required
services:
	- docker
	
before_install:
	- docker build -t alessiottavo/docker-reactor -f Dockerfile.dev .
	
script:
	script:
	  - docker run alessiottavo/docker-reactor mvn clean install
