# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

RUN apt-get update && \
    apt-get install -y maven

# Set the working directory in the container
WORKDIR /app

# Copy the pom.xml and maven configuration files to the container
COPY pom.xml mvnw ./
COPY .mvn .mvn

# Download the dependencies without caching the package contents
RUN ./mvnw dependency:go-offline

# Copy the project source to the container
COPY src src

# Build the project
RUN ./mvnw package -DskipTests

# Expose the port the app runs on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "target/reactive-programming-with-reactor-3-0.0.1-SNAPSHOT.jar"]